site_name: Dashboard
theme:
  name: material
nav:
  - Introduction: 'index.md'
  - Serveur: 'serveur.md'
  - Client: 'client.md'
  - Déploiement: 'deploy.md'
  - Prédictions: 'predictions.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
