site_name: Tableau Électrique Citoyen — Documentation Développeur
theme:
  name: material
nav:
  - Introduction: 'index.md'
  - Serveur: 'serveur.md'
  - Client: 'client.md'
  - Prédictions: 'predictions.md'
  - Infrastructure: 'infrastructure.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
