export enum ConsumerProfile {
	ALL = 'ALL',
	RESIDENTIAL = 'RESIDENTIAL',
	PROFESSIONAL = 'PROFESSIONAL',
	TERTIARY = 'TERTIARY',
	PUBLIC_LIGHTING = 'PUBLIC_LIGHTING'
}

export enum ProducerProfile {
	BIOENERGY = 'BIOENERGY',
	EOLIAN = 'EOLIAN',
	HYDRAULIC = 'HYDRAULIC',
	NON_RENEWABLE_THERMAL = 'NON_RENEWABLE_THERMAL',
	OTHER = 'OTHER',
	SOLAR = 'SOLAR',
	TOTAL = 'TOTAL',
}

export enum DataType {
	CONSUMPTION = 'CONSUMPTION',
	PRODUCTION = 'PRODUCTION',
}
