var json_BornesVE_Bordeaux_Bastide = {
    "type": "FeatureCollection",
    "name": "BornesVE_Bordeaux_Bastide",
    "crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:OGC:1.3:CRS84"}},
    "features": [
        {
            "type": "Feature", "properties": {
                "ID ZONE": 24058,
                "D�partement": 33,
                "Adresse Ville": "Bordeaux",
                "Adresse CP": 33100,
                "Adresse Code INSEE 2018": 33063,
                "Adresse N�": "2",
                "Adresse Voie": "Rue Honor� Picon",
                "latitude": 44.841123,
                "longitude": -0.55964,
                "Propri�taire": "Blue Solutions",
                "Exploitant technique": "Bluecub | FR*E62",
                "Exploitant commercial": "",
                "Autopartage sur zone": "oui",
                "Type de site": "Station en voirie",
                "Statut de la zone": "En service",
                "Date de mise en service": "Inconnu",
                "Horaires d'ouverture": "24\/7",
                "Accessibilit� de la zone": "Acc�s ouvert au public",
                "Nb. de bornes total": 5,
                "Nb. de pdc non contr�l�s et libres tout public": 0,
                "Nombre de PDC Total": 5,
                "Nb.de PDC 3,7KVA": 5,
                "Nb.de PDC 7KVA": 0,
                "Nb.de PDC 11KVA": 0,
                "Nb.de PDC 18KVA": 0,
                "Nb.de PDC 20KVA": 0,
                "Nb.de PDC 22KVA": 0,
                "Nb. de PDC 43KVA": 0,
                "Nb.de PDC 50KVA": 0,
                "Nb.de PDC 120KVA": 0,
                "Prise E\/F": 1,
                "Prise Type 2": 0,
                "Prise Type 3": 5,
                "Prise indust. bleue": 0,
                "Prise indust. rouge": 0,
                "C�ble Type 1": 5,
                "C�ble Type 2": 0,
                "C�ble CHAdeMO": 0,
                "C�ble Combo": 0,
                "C�ble Tesla (T2)": 0,
                "C�ble Tesla Roadster": 0,
                "C�ble Marechal": 0,
                "ID Gireve Propri�taire": "2698"
            }, "geometry": {"type": "Point", "coordinates": [-0.55964, 44.841123]}
        },
        {
            "type": "Feature", "properties": {
                "ID ZONE": 2934,
                "D�partement": 33,
                "Adresse Ville": "Bordeaux",
                "Adresse CP": 33100,
                "Adresse Code INSEE 2018": 33063,
                "Adresse N�": "87",
                "Adresse Voie": "Quai des Queyries",
                "latitude": 44.849957,
                "longitude": -0.560872,
                "Propri�taire": "Blue Solutions",
                "Exploitant technique": "Bluecub | FR*E62",
                "Exploitant commercial": "",
                "Autopartage sur zone": "oui",
                "Type de site": "Station en voirie",
                "Statut de la zone": "En service",
                "Date de mise en service": "Inconnu",
                "Horaires d'ouverture": "24\/7",
                "Accessibilit� de la zone": "Acc�s ouvert au public",
                "Nb. de bornes total": 5,
                "Nb. de pdc non contr�l�s et libres tout public": 0,
                "Nombre de PDC Total": 5,
                "Nb.de PDC 3,7KVA": 5,
                "Nb.de PDC 7KVA": 0,
                "Nb.de PDC 11KVA": 0,
                "Nb.de PDC 18KVA": 0,
                "Nb.de PDC 20KVA": 0,
                "Nb.de PDC 22KVA": 0,
                "Nb. de PDC 43KVA": 0,
                "Nb.de PDC 50KVA": 0,
                "Nb.de PDC 120KVA": 0,
                "Prise E\/F": 1,
                "Prise Type 2": 0,
                "Prise Type 3": 5,
                "Prise indust. bleue": 0,
                "Prise indust. rouge": 0,
                "C�ble Type 1": 5,
                "C�ble Type 2": 0,
                "C�ble CHAdeMO": 0,
                "C�ble Combo": 0,
                "C�ble Tesla (T2)": 0,
                "C�ble Tesla Roadster": 0,
                "C�ble Marechal": 0,
                "ID Gireve Propri�taire": "2698"
            }, "geometry": {"type": "Point", "coordinates": [-0.560872, 44.849957]}
        },
        {
            "type": "Feature", "properties": {
                "ID ZONE": 74969,
                "D�partement": 33,
                "Adresse Ville": "Bordeaux",
                "Adresse CP": 33100,
                "Adresse Code INSEE 2018": 33063,
                "Adresse N�": "6",
                "Adresse Voie": "All�e Serr",
                "latitude": 44.8414,
                "longitude": -0.56097,
                "Propri�taire": "Bordeaux M�tropole",
                "Exploitant technique": "Freshmile Services | FR*FR1",
                "Exploitant commercial": "",
                "Autopartage sur zone": "non",
                "Type de site": "Station en voirie",
                "Statut de la zone": "En service",
                "Date de mise en service": "Inconnu",
                "Horaires d'ouverture": "24\/7",
                "Accessibilit� de la zone": "Acc�s ouvert au public",
                "Nb. de bornes total": 1,
                "Nb. de pdc non contr�l�s et libres tout public": 0,
                "Nombre de PDC Total": 4,
                "Nb.de PDC 3,7KVA": 0,
                "Nb.de PDC 7KVA": 0,
                "Nb.de PDC 11KVA": 0,
                "Nb.de PDC 18KVA": 0,
                "Nb.de PDC 20KVA": 0,
                "Nb.de PDC 22KVA": 0,
                "Nb. de PDC 43KVA": 0,
                "Nb.de PDC 50KVA": 4,
                "Nb.de PDC 120KVA": 0,
                "Prise E\/F": 4,
                "Prise Type 2": 0,
                "Prise Type 3": 0,
                "Prise indust. bleue": 0,
                "Prise indust. rouge": 0,
                "C�ble Type 1": 0,
                "C�ble Type 2": 4,
                "C�ble CHAdeMO": 2,
                "C�ble Combo": 2,
                "C�ble Tesla (T2)": 0,
                "C�ble Tesla Roadster": 0,
                "C�ble Marechal": 0,
                "ID Gireve Propri�taire": "8825"
            }, "geometry": {"type": "Point", "coordinates": [-0.56097, 44.8414]}
        },
        {
            "type": "Feature", "properties": {
                "ID ZONE": 74972,
                "D�partement": 33,
                "Adresse Ville": "Bordeaux",
                "Adresse CP": 33100,
                "Adresse Code INSEE 2018": 33063,
                "Adresse N�": "65",
                "Adresse Voie": "Rue Henri Dunant",
                "latitude": 44.8402,
                "longitude": -0.55604,
                "Propri�taire": "Bordeaux M�tropole",
                "Exploitant technique": "Freshmile Services | FR*FR1",
                "Exploitant commercial": "",
                "Autopartage sur zone": "non",
                "Type de site": "Station en voirie",
                "Statut de la zone": "En service",
                "Date de mise en service": "Inconnu",
                "Horaires d'ouverture": "24\/7",
                "Accessibilit� de la zone": "Acc�s ouvert au public",
                "Nb. de bornes total": 1,
                "Nb. de pdc non contr�l�s et libres tout public": 0,
                "Nombre de PDC Total": 4,
                "Nb.de PDC 3,7KVA": 0,
                "Nb.de PDC 7KVA": 0,
                "Nb.de PDC 11KVA": 0,
                "Nb.de PDC 18KVA": 0,
                "Nb.de PDC 20KVA": 0,
                "Nb.de PDC 22KVA": 0,
                "Nb. de PDC 43KVA": 0,
                "Nb.de PDC 50KVA": 4,
                "Nb.de PDC 120KVA": 0,
                "Prise E\/F": 4,
                "Prise Type 2": 0,
                "Prise Type 3": 0,
                "Prise indust. bleue": 0,
                "Prise indust. rouge": 0,
                "C�ble Type 1": 0,
                "C�ble Type 2": 4,
                "C�ble CHAdeMO": 2,
                "C�ble Combo": 2,
                "C�ble Tesla (T2)": 0,
                "C�ble Tesla Roadster": 0,
                "C�ble Marechal": 0,
                "ID Gireve Propri�taire": "8825"
            }, "geometry": {"type": "Point", "coordinates": [-0.55604, 44.8402]}
        }
    ]
}
